### ISSUE TITLE
AttributeError: 'mOTU' object has no attribute 'members'

### ISSUE THREAD

**Issue by wyim-pgl** [fpusan/SuperPang#18]
Dear SuperPang,
We are working on a plant genome to create a core chromosome set. To begin, we selected one chromosome from three different assemblies and trimmed the initial sequences (using head -n 4000~6000, with a FASTA width of 60, resulting in sequences around 239kbp to 359kbp in length). These chromosomes have high similarity in terms of gene content, and each three FASTA header is unique. When running SuperPang with the command below, we encountered an error.

`
SuperPang.py -f ./*.fasta --threads 5 --gap-size 1  --force-overwrite --output-dir aa --debug --verbose-mOTUpan
`

The log is provided below. It seems it couldn't correct sequences. It ended up with mOTU error.

Could you please assist us in resolving this issue? It doesn't seem to be working on our end. 
input file has been attached. 
[Downloads.zip](https://github.com/user-attachments/files/16955762/Downloads.zip)

```
This is SuperPang version 1.3.1

If using in publications or products please cite:

Puente-Sánchez F, Hoetzinger M, Buck M and Bertilsson S. Exploring intra-species diversity through non-redundant pangenome assemblies. Molecular Ecology Resources (2023) DOI: 10.1111/1755-0998.13826

Running in debug mode. Execution speed will be slower...


/data/gpfs/assoc/pgl/bin/miniconda3/envs/SuperPang/lib/python3.12/site-packages/SuperPang-1.3.1-py3.12-linux-x86_64.egg/superpang/scripts/homogenize.py:267: SyntaxWarning: invalid escape sequence '\d'
  cigar   = re.split('(\d+)',cigar)[1:]
10/09/2024 15:40:51     180MB   Correcting input sequences with minimap2
10/09/2024 15:40:51     180MB   round   correctedFull   correctedPartial        mismatches    indels   errors
10/09/2024 15:40:55     180MB   1       0       0       0       0       0
10/09/2024 15:41:00     180MB   2       0       0       0       0       0
10/09/2024 15:41:05     180MB   3       0       0       0       0       0
10/09/2024 15:41:10     180MB   4       0       0       0       0       0
10/09/2024 15:41:14     180MB   5       0       0       0       0       0
10/09/2024 15:41:14     180MB   Reading sequences
10/09/2024 15:41:14     181MB   Allocating resources
10/09/2024 15:41:14     187MB   Creating DBG from 12 sequences (3 originals)
10/09/2024 15:41:15     190MB           1.0% bases processed, 1 sequences, 8270 vertices, 8269 10/09/2024 15:41:15     192MB           2.0% bases processed, 1 sequences, 16782 vertices, 167810/09/2024 15:41:15     194MB           3.0% bases processed, 2 sequences, 25052 vertices, 250510/09/2024 15:41:15     196MB           4.0% bases processed, 2 sequences, 33622 vertices, 336210/09/2024 15:41:16     197MB           5.0% bases processed, 2 sequences, 42192 vertices, 421910/09/2024 15:41:17     201MB           6.0% bases processed, 3 sequences, 50462 vertices, 504610/09/2024 15:41:17     203MB           7.0% bases processed, 3 sequences, 59032 vertices, 590310/09/2024 15:41:17     204MB           8.0% bases processed, 3 sequences, 67602 vertices, 676010/09/2024 15:41:17     205MB           9.0% bases processed, 3 sequences, 76054 vertices, 760510/09/2024 15:41:17     207MB           10.0% bases processed, 3 sequences, 84624 vertices, 84610/09/2024 15:41:17     213MB           11.0% bases processed, 3 sequences, 93194 vertices, 93110/09/2024 15:41:18     213MB           12.0% bases processed, 3 sequences, 101764 vertices, 1010/09/2024 15:41:18     215MB           13.0% bases processed, 3 sequences, 110334 vertices, 1110/09/2024 15:41:18     217MB           14.0% bases processed, 3 sequences, 118843 vertices, 1110/09/2024 15:41:18     219MB           15.0% bases processed, 3 sequences, 127413 vertices, 1210/09/2024 15:41:18     221MB           16.0% bases processed, 3 sequences, 135983 vertices, 1310/09/2024 15:41:18     223MB           17.0% bases processed, 3 sequences, 144553 vertices, 1410/09/2024 15:41:18     225MB           18.0% bases processed, 3 sequences, 153123 vertices, 1510/09/2024 15:41:18     227MB           19.0% bases processed, 3 sequences, 161693 vertices, 1610/09/2024 15:41:18     228MB           20.0% bases processed, 3 sequences, 170263 vertices, 1710/09/2024 15:41:18     239MB           21.0% bases processed, 3 sequences, 178833 vertices, 1710/09/2024 15:41:19     239MB           22.0% bases processed, 4 sequences, 186733 vertices, 1810/09/2024 15:41:19     239MB           23.0% bases processed, 4 sequences, 195303 vertices, 1910/09/2024 15:41:19     239MB           24.0% bases processed, 4 sequences, 203873 vertices, 2010/09/2024 15:41:19     241MB           25.0% bases processed, 4 sequences, 212443 vertices, 2110/09/2024 15:41:19     242MB           26.0% bases processed, 4 sequences, 221013 vertices, 2210/09/2024 15:41:19     245MB           27.0% bases processed, 4 sequences, 229583 vertices, 2210/09/2024 15:41:20     247MB           28.0% bases processed, 5 sequences, 237853 vertices, 2310/09/2024 15:41:20     247MB           29.0% bases processed, 5 sequences, 246354 vertices, 2410/09/2024 15:41:20     249MB           30.0% bases processed, 5 sequences, 254607 vertices, 2510/09/2024 15:41:20     250MB           31.0% bases processed, 5 sequences, 263177 vertices, 2610/09/2024 15:41:20     251MB           32.0% bases processed, 5 sequences, 271747 vertices, 2710/09/2024 15:41:20     252MB           33.0% bases processed, 5 sequences, 280317 vertices, 2810/09/2024 15:41:20     253MB           34.0% bases processed, 5 sequences, 288887 vertices, 2810/09/2024 15:41:20     255MB           35.0% bases processed, 5 sequences, 297457 vertices, 2910/09/2024 15:41:20     256MB           36.0% bases processed, 5 sequences, 306027 vertices, 3010/09/2024 15:41:20     257MB           37.0% bases processed, 5 sequences, 314597 vertices, 3110/09/2024 15:41:23     259MB           38.0% bases processed, 6 sequences, 322867 vertices, 3210/09/2024 15:41:23     260MB           39.0% bases processed, 6 sequences, 331430 vertices, 3310/09/2024 15:41:23     262MB           40.0% bases processed, 6 sequences, 340000 vertices, 3410/09/2024 15:41:23     263MB           41.0% bases processed, 6 sequences, 348570 vertices, 3410/09/2024 15:41:23     283MB           42.0% bases processed, 6 sequences, 357140 vertices, 3510/09/2024 15:41:23     283MB           43.0% bases processed, 6 sequences, 365710 vertices, 3610/09/2024 15:41:23     283MB           44.0% bases processed, 6 sequences, 374280 vertices, 3710/09/2024 15:41:23     283MB           45.0% bases processed, 6 sequences, 382850 vertices, 3810/09/2024 15:41:23     283MB           46.0% bases processed, 6 sequences, 391420 vertices, 3910/09/2024 15:41:23     283MB           47.0% bases processed, 6 sequences, 399990 vertices, 3910/09/2024 15:41:23     283MB           48.0% bases processed, 6 sequences, 408560 vertices, 4010/09/2024 15:41:23     283MB           49.0% bases processed, 6 sequences, 417130 vertices, 4110/09/2024 15:41:23     284MB           50.0% bases processed, 6 sequences, 425700 vertices, 4210/09/2024 15:41:23     285MB           51.0% bases processed, 6 sequences, 434270 vertices, 4310/09/2024 15:41:23     286MB           52.0% bases processed, 6 sequences, 442840 vertices, 4410/09/2024 15:41:23     287MB           53.0% bases processed, 6 sequences, 451410 vertices, 4510/09/2024 15:41:23     288MB           54.01% bases processed, 6 sequences, 459980 vertices, 410/09/2024 15:41:23     290MB           55.01% bases processed, 6 sequences, 468441 vertices, 410/09/2024 15:41:23     292MB           56.01% bases processed, 6 sequences, 476640 vertices, 410/09/2024 15:41:23     293MB           57.01% bases processed, 6 sequences, 482308 vertices, 410/09/2024 15:41:23     297MB           58.01% bases processed, 6 sequences, 490744 vertices, 410/09/2024 15:41:24     297MB           59.01% bases processed, 7 sequences, 491164 vertices, 410/09/2024 15:41:24     297MB           60.01% bases processed, 7 sequences, 491164 vertices, 410/09/2024 15:41:24     297MB           61.01% bases processed, 8 sequences, 491164 vertices, 410/09/2024 15:41:24     297MB           62.01% bases processed, 8 sequences, 491164 vertices, 410/09/2024 15:41:24     297MB           63.01% bases processed, 8 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           64.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           65.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           66.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           67.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           68.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           69.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           70.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           71.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           72.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           73.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           74.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           75.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           76.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           77.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           78.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:26     299MB           79.01% bases processed, 9 sequences, 491164 vertices, 410/09/2024 15:41:28     299MB           80.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           81.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           82.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           83.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           84.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           85.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     299MB           86.01% bases processed, 10 sequences, 491164 vertices, 10/09/2024 15:41:28     300MB           87.01% bases processed, 10 sequences, 499634 vertices, 10/09/2024 15:41:28     301MB           88.01% bases processed, 10 sequences, 508204 vertices, 10/09/2024 15:41:28     302MB           89.01% bases processed, 10 sequences, 516774 vertices, 10/09/2024 15:41:28     303MB           90.01% bases processed, 10 sequences, 525344 vertices, 10/09/2024 15:41:28     305MB           91.01% bases processed, 10 sequences, 533914 vertices, 10/09/2024 15:41:28     306MB           92.01% bases processed, 10 sequences, 542484 vertices, 10/09/2024 15:41:28     307MB           93.01% bases processed, 10 sequences, 551054 vertices, 10/09/2024 15:41:29     308MB           94.01% bases processed, 11 sequences, 558905 vertices, 10/09/2024 15:41:29     309MB           95.01% bases processed, 11 sequences, 566988 vertices, 10/09/2024 15:41:29     310MB           96.01% bases processed, 11 sequences, 574880 vertices, 10/09/2024 15:41:29     311MB           97.01% bases processed, 11 sequences, 583309 vertices, 10/09/2024 15:41:29     312MB           98.01% bases processed, 11 sequences, 591810 vertices, 10/09/2024 15:41:29     314MB           99.01% bases processed, 11 sequences, 600380 vertices, 10/09/2024 15:41:35     315MB           100% bases processed, 11 sequences, 608679 vertices, 608716 edges
10/09/2024 15:41:35     315MB   Identifying connected components
10/09/2024 15:41:35     315MB   Working on comp 1/3, 305842 vertices
10/09/2024 15:41:35     315MB           Collecting non-branching paths
10/09/2024 15:41:38     315MB           Building sequence graph out of 224 non-branching paths
10/09/2024 15:41:39     315MB           Extracting forward component
10/09/2024 15:41:40     315MB           Scaffold 0, 112 NBP vertices, 146 NBP edges, 306478 bas10/09/2024 15:41:41     315MB           Scaffold 0, 112 NBP vertices, 146 NBP edges, 306478 bas10/09/2024 15:41:41les  322MB           Scaffold 0, 112 NBP vertices, 146 NBP edges, 306478 bas10/09/2024 15:41:42les, 322MBssing 82 noScaffold 0, 112 NBP vertices, 146 NBP edges, 306478 bases, removed 10 bubbles, processing 82 non-branching paths, done
10/09/2024 15:41:42     322MB   Working on comp 2/3, 185743 vertices
10/09/2024 15:41:42     322MB           Collecting non-branching paths
10/09/2024 15:41:45     330MB           Building sequence graph out of 42 non-branching paths
10/09/2024 15:41:46     332MB           Extracting forward component
10/09/2024 15:41:47     346MB           Scaffold 1, 21 NBP vertices, 24 NBP edges, 186649 bases10/09/2024 15:41:47     346MB           Scaffold 1, 21 NBP vertices, 24 NBP edges, 186649 bases10/09/2024 15:41:48, pro356MBng 21 non-bScaffold 1, 21 NBP vertices, 24 NBP edges, 186649 bases, removed 0 bubbles, processing 21 non-branching paths, done
10/09/2024 15:41:48     356MB   Working on comp 3/3, 117094 vertices
10/09/2024 15:41:48     356MB           Collecting non-branching paths
10/09/2024 15:41:49     359MB           Building sequence graph out of 8 non-branching paths
10/09/2024 15:41:50     399MB           Extracting forward component
10/09/2024 15:41:50     399MB           Scaffold 2, 4 NBP vertices, 4 NBP edges, 117395 bases, 10/09/2024 15:41:50     399MB           Scaffold 2, 4 NBP vertices, 4 NBP edges, 117395 bases, 10/09/2024 15:41:50proce399MB 4 non-branScaffold 2, 4 NBP vertices, 4 NBP edges, 117395 bases, removed 0 bubbles, processing 4 non-branching paths, done
10/09/2024 15:41:50     399MB   Running mOTUpan
Traceback (most recent call last):
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/bin/SuperPang.py", line 33, in <module>
    sys.exit(load_entry_point('SuperPang==1.3.1', 'console_scripts', 'SuperPang.py')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/lib/python3.12/site-packages/SuperPang-1.3.1-py3.12-linux-x86_64.egg/superpang/scripts/SuperPang.py", line 392, in cli
    main(args, uuid)
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/lib/python3.12/site-packages/SuperPang-1.3.1-py3.12-linux-x86_64.egg/superpang/scripts/SuperPang.py", line 234, in main
    if motu.get_stats()['mOTUpan_core_prediction']['core']:
       ^^^^^^^^^^^^^^^^
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/lib/python3.12/site-packages/mOTUlizer-0.3.4-py3.12.egg/mOTUlizer/classes/mOTU.py", line 165, in get_stats
    out[self.name] = { "nb_genomes" : len(self),
                                      ^^^^^^^^^
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/lib/python3.12/site-packages/mOTUlizer-0.3.4-py3.12.egg/mOTUlizer/classes/mOTU.py", line 18, in __len__
    return len(self.members)
               ^^^^^^^^^^^^
AttributeError: 'mOTU' object has no attribute 'members'
```

In addition, we test mOTUlize.py as below.
```
mOTUlize.py --fnas *.fasta  -o output.tsv
/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/bin/mOTUlize.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('mOTUlizer==0.2.4', 'mOTUlize.py')
3 genomes found
Parsing the completeness/redundancy-file
No file provided, all genomes are assumed perfect (100% complete, 0% redundancy)
making bin-objects
Similarities not provided, will compute them with fastANI
doing bloc 0 and 0
making mOTUs
seeding bin-graph
getting clusters
recruiting to graph of the 1  mOTUs of mean length 3.0
looking for good_left pairs
looking for best mOTU match
append to the 1 mOTUs of mean length 3.0
processing the 1 mOTUs of mean length 3.0
making stats
```

**Comment by fpusan** [comment]
Do you have the right version of mOTUlizer (0.2.4)?

**Comment by wyim-pgl** [comment]
We installed mOTUlizer version 0.2.4 via Conda, but encountered the same error during testing. Additionally, after updating to the latest version of mOTUlizer from GitHub, the error persisted.

```
mOTUlize.py --fnas *.fasta  -o output.tsv
/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/SuperPang/bin/mOTUlize.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('mOTUlizer==0.2.4', 'mOTUlize.py')
3 genomes found
Parsing the completeness/redundancy-file
No file provided, all genomes are assumed perfect (100% complete, 0% redundancy)
making bin-objects
Similarities not provided, will compute them with fastANI
doing bloc 0 and 0
making mOTUs
seeding bin-graph
getting clusters
recruiting to graph of the 1  mOTUs of mean length 3.0
looking for good_left pairs
looking for best mOTU match
append to the 1 mOTUs of mean length 3.0
processing the 1 mOTUs of mean length 3.0
making stats

```

**Comment by fpusan** [comment]
Does it also happen when you run `test-SuperPang.py`?

**Comment by fpusan** [comment]
Closing due to lack of activity, feel free to reopen
