### ISSUE TITLE
Error Running Homogenize.py

### ISSUE THREAD

**Issue by shnv-dnl** [fpusan/SuperPang#19]
Hi, I've been getting an error with SuperPang whenever I try to run it. Here's the full error code

Traceback (most recent call last):
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/scripts/homogenize.py", line 369, in <module>
    cli()
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/scripts/homogenize.py", line 365, in cli
    main(parse_args())
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/scripts/homogenize.py", line 38, in main
    mLen, iLen, oLen, corrected_thisround, nErrors = iterate(args, rounds, prefix, current1, current2, corrected, correction_tries,
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/scripts/homogenize.py", line 72, in iterate
    seqs = read_fastq(infastq, ambigs = 'as_Ns')
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/lib/utils.py", line 41, in read_fastq
    seq = fix_Ns(seq)
  File "/usr/local/envs/SuperPang/lib/python3.8/site-packages/superpang/lib/utils.py", line 58, in fix_Ns
    raise ValueError(f'Illegal chars in seq "{name}": {badChars}')
NameError: name 'name' is not defined

There was an error running homogenize.py. Please open an issue

**Comment by fpusan** [comment]
Ok, there are two problems here:
- One of your input sequences have a base that is not 'A', 'C', 'T', 'G', or 'N'. Probably some ambiguity code other than N.
- There is a bug in the code that tries to write the error message informing of this.

Can you run the following one-liner to fix each of your fasta files so they only have ACTGN, and try SuperPang again with the new files?

`perl -pe 's/[^AGTC\n]/N/gi unless m/>/;'  old.fa > new.fa`

**Comment by fpusan** [comment]
Alternatively
`sed '/^[^>]/ s/[^AGTC]/N/gi' < seq.fa` should also work

**Comment by shnv-dnl** [comment]
Hello,

It worked! Thank you so much for the assistance.

Best wishes,
Shaanaav Daniel
