### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yi1873** [fpusan/SuperPang#4]
Error in ".../anaconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/Assembler.py", line 829, in reconstruct_sequence
    if k[:-1] == kmers[-1][1:]:
IndexError: list index out of range

**Comment by fpusan** [comment]
Hi!
Can you share the input genomes and the command you used so I can try to reproduce the error?

**Comment by yi1873** [comment]
Species: Mycobacterium tuberculosis
Taxid: 1773
Genome：316 complete genomes in GenBank (https://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt)
Command: SuperPang.py --fasta genome/*.fa  --output-dir 1773/pangenome --force-overwrite -t 20  --assume-complete -b 0.95 -i 0.95 -k 301

**Comment by yi1873** [comment]
You can also test E.coli with all complete genomes in GenBank, get the same error.

**Comment by fpusan** [comment]
Can reproduce with the Mycobacterium tuberculosis dataset

**Comment by yi1873** [comment]
**Full errors:**

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File ".../anaconda3/envs/SuperPang/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File ".../anaconda3/envs/SuperPang/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File ".../anaconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/Assembler.py", line 846, in reconstruct_sequence
    if k[:-1] == kmers[-1][1:]:
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../anaconda3/envs/SuperPang/bin/SuperPang.py", line 291, in <module>
    main(parse_args())
  File ".../anaconda3/envs/SuperPang/bin/SuperPang.py", line 144, in main
    contigs = Assembler(input_minimap2, args.ksize, args.threads).run(args.minlen, args.mincov, args.bubble_identity_threshold, args.genome_assignment_threshold, args.threads)
  File ".../anaconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/Assembler.py", line 259, in run
    NBP2seq = dict(zip(NBPs, self.multimap(self.reconstruct_sequence, threads, NBPs, self.vertex2hash, self.compressor)))
  File ".../anaconda3/envs/SuperPang/lib/python3.8/site-packages/SuperPang/lib/Assembler.py", line 55, in multimap
    res = pool.map(fun, range(len(iterable)))
  File ".../anaconda3/envs/SuperPang/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File ".../anaconda3/envs/SuperPang/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

**Comment by fpusan** [comment]
Thanks! I'm running it right now in my computers, adding some traces to see what could be happening.
Also, wild guess here, but does this also happen if you call it like
`SuperPang.py --fasta genome/*.fa --output-dir 1773/pangenome --force-overwrite -t 20 --assume-complete -b 0.95 -i 0.95 -k 301 -n 20` ?

**Comment by fpusan** [comment]
Nevermind, I now think that the problem is due to the presence of ambiguous bases in the input fasta files
(e.g. "M" to represent either "A" or "C"). This happens for these genomes and would definitely break my code in a few places. Will think of a fix

**Comment by fpusan** [comment]
Hi again! This issue is hopefully fixed in the new version 0.9.3
